// Core types for the Browser Candidate Search Agent

export interface PageElement {
  ref: string;           // "link_1", "btn_2", "input_3"
  type: 'link' | 'button' | 'input' | 'textarea' | 'select';
  text: string;          // Visible text or placeholder
  selector: string;      // CSS selector for Playwright
  href?: string;         // For links only
}

export interface PageContext {
  url: string;
  title: string;
  elements: PageElement[];
  textContent?: string;  // Summarized page text (truncated)
}

export interface SocialLinks {
  github?: string;
  twitter?: string;
  linkedin?: string;
  website?: string;
  email?: string;
  telegram?: string;
  discord?: string;
  stackoverflow?: string;
  medium?: string;
  dev?: string;
  youtube?: string;
  other?: string[];
}

export interface Candidate {
  username: string;
  profileUrl: string;
  name?: string;
  bio?: string;
  location?: string;
  topLanguages: string[];
  repos?: number;
  followers?: number;
  matchReason: string;
  // New fields for enhanced profile data
  socialLinks?: SocialLinks;
  website?: string;
  tldrSummary?: string;  // Generated by sub-agent after deep scan
  company?: string;
  hireable?: boolean;
  skills?: string[];
  experience?: string[];
}

// Sub-agent scan result
export interface ProfileScanResult {
  success: boolean;
  profileUrl: string;
  socialLinks: SocialLinks;
  tldrSummary: string;
  additionalData?: {
    tabs?: string[];
    pinnedRepos?: string[];
    contributions?: string;
    organizations?: string[];
    achievements?: string[];
  };
}

export interface ScanProfileArgs {
  profileUrl: string;
  username: string;
}

export interface TaskResult {
  success: boolean;
  candidates: Candidate[];
  summary: string;
}

// Tool argument types
export interface NavigateArgs {
  url: string;
}

export interface ClickArgs {
  ref: string;
}

export interface TypeTextArgs {
  ref: string;
  text: string;
  pressEnter?: boolean;
}

export interface ScrollArgs {
  direction: 'up' | 'down';
}

export interface TaskCompleteArgs {
  candidates: Candidate[];
  summary: string;
}

export interface AskUserArgs {
  question: string;
}

export interface RequestConfirmationArgs {
  action: string;
  reason: string;
  impact: string;
}

// Agent message types
export interface AgentMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string | null;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
}

export interface ToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    arguments: string;
  };
}

// Tool execution result
export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
}
